name: "React Native Doctor"
description: "Scan React Native & Expo codebases for performance, accessibility, and architecture issues"
branding:
  icon: "activity"
  color: "blue"

inputs:
  directory:
    description: "Project directory to scan"
    default: "."
  verbose:
    description: "Show file details per rule"
    default: "true"
  project:
    description: "Workspace project(s) to scan (comma-separated)"
    required: false
  rn-only:
    description: "Force-enable React Native rules even if react-native is not auto-detected"
    default: "false"
  expo-only:
    description: "Force-enable Expo rules even if expo is not auto-detected"
    default: "false"
  node-version:
    description: "Node.js version to use"
    default: "20"

outputs:
  score:
    description: "Health score (0-100)"
    value: ${{ steps.score.outputs.score }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_RN_ONLY: ${{ inputs.rn-only }}
        INPUT_EXPO_ONLY: ${{ inputs.expo-only }}
      run: |
        FLAGS=""
        if [ "$INPUT_VERBOSE" = "true" ]; then FLAGS="$FLAGS --verbose"; fi
        if [ -n "$INPUT_PROJECT" ]; then FLAGS="$FLAGS --project $INPUT_PROJECT"; fi
        if [ "$INPUT_RN_ONLY" = "true" ]; then FLAGS="$FLAGS --rn-only"; fi
        if [ "$INPUT_EXPO_ONLY" = "true" ]; then FLAGS="$FLAGS --expo-only"; fi
        npx -y react-native-doc@latest "$INPUT_DIRECTORY" $FLAGS

    - id: score
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
      run: |
        SCORE=$(npx -y react-native-doc@latest "$INPUT_DIRECTORY" --score 2>/dev/null || echo "")
        echo "score=$SCORE" >> "$GITHUB_OUTPUT"
